language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install -e .[fulldev]
script:
  - pytest --cov clac tests
  - pylint clac
  - mypy clac
after_success:
  - codecov