language: python
python: "3.6"
cache: pip
install:
  - pip install -e .[fulldev]
script:
  - pytest --cov clac tests
  - pylint clac
  - mypy clac
  - sphinx-build -M html docs/source docs/build
after_success:
  - codecov
